
ichimoku_12_30_45_20:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 45
  chikou_shift: 20

ichimoku_12_30_45_26:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 45
  chikou_shift: 26

ichimoku_12_30_45_30:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 45
  chikou_shift: 30

ichimoku_12_30_52_20:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 52
  chikou_shift: 20

ichimoku_12_30_52_26:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 52
  chikou_shift: 26

ichimoku_12_30_52_30:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 52
  chikou_shift: 30

ichimoku_12_30_60_20:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 60
  chikou_shift: 20

ichimoku_12_30_60_26:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 60
  chikou_shift: 26

ichimoku_12_30_60_30:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 60
  chikou_shift: 30

ichimoku_12_30_70_20:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 70
  chikou_shift: 20

ichimoku_12_30_70_26:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 70
  chikou_shift: 26

ichimoku_12_30_70_30:
  tenkan_period: 12
  kijun_period: 30
  senkou_b_period: 70
  chikou_shift: 30
