
ichimoku_9_20_45_20:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 45
  chikou_shift: 20

ichimoku_9_20_45_26:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 45
  chikou_shift: 26

ichimoku_9_20_45_30:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 45
  chikou_shift: 30

ichimoku_9_20_52_20:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 52
  chikou_shift: 20

ichimoku_9_20_52_26:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 52
  chikou_shift: 26

ichimoku_9_20_52_30:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 52
  chikou_shift: 30

ichimoku_9_20_60_20:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 60
  chikou_shift: 20

ichimoku_9_20_60_26:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 60
  chikou_shift: 26

ichimoku_9_20_60_30:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 60
  chikou_shift: 30

ichimoku_9_20_70_20:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 70
  chikou_shift: 20

ichimoku_9_20_70_26:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 70
  chikou_shift: 26

ichimoku_9_20_70_30:
  tenkan_period: 9
  kijun_period: 20
  senkou_b_period: 70
  chikou_shift: 30
