
macd_10_20_6:
  fast: 10
  slow: 20
  signal: 6

macd_10_20_9:
  fast: 10
  slow: 20
  signal: 9

macd_10_20_12:
  fast: 10
  slow: 20
  signal: 12

macd_10_24_6:
  fast: 10
  slow: 24
  signal: 6

macd_10_24_9:
  fast: 10
  slow: 24
  signal: 9

macd_10_24_12:
  fast: 10
  slow: 24
  signal: 12

macd_10_26_6:
  fast: 10
  slow: 26
  signal: 6

macd_10_26_9:
  fast: 10
  slow: 26
  signal: 9

macd_10_26_12:
  fast: 10
  slow: 26
  signal: 12

macd_10_28_6:
  fast: 10
  slow: 28
  signal: 6

macd_10_28_9:
  fast: 10
  slow: 28
  signal: 9

macd_10_28_12:
  fast: 10
  slow: 28
  signal: 12

macd_10_30_6:
  fast: 10
  slow: 30
  signal: 6

macd_10_30_9:
  fast: 10
  slow: 30
  signal: 9

macd_10_30_12:
  fast: 10
  slow: 30
  signal: 12
