
macd_12_20_6:
  fast: 12
  slow: 20
  signal: 6

macd_12_20_9:
  fast: 12
  slow: 20
  signal: 9

macd_12_20_12:
  fast: 12
  slow: 20
  signal: 12

macd_12_24_6:
  fast: 12
  slow: 24
  signal: 6

macd_12_24_9:
  fast: 12
  slow: 24
  signal: 9

macd_12_24_12:
  fast: 12
  slow: 24
  signal: 12

macd_12_26_6:
  fast: 12
  slow: 26
  signal: 6

macd_12_26_9:
  fast: 12
  slow: 26
  signal: 9

macd_12_26_12:
  fast: 12
  slow: 26
  signal: 12

macd_12_28_6:
  fast: 12
  slow: 28
  signal: 6

macd_12_28_9:
  fast: 12
  slow: 28
  signal: 9

macd_12_28_12:
  fast: 12
  slow: 28
  signal: 12

macd_12_30_6:
  fast: 12
  slow: 30
  signal: 6

macd_12_30_9:
  fast: 12
  slow: 30
  signal: 9

macd_12_30_12:
  fast: 12
  slow: 30
  signal: 12
