
macd_16_20_6:
  fast: 16
  slow: 20
  signal: 6

macd_16_20_9:
  fast: 16
  slow: 20
  signal: 9

macd_16_20_12:
  fast: 16
  slow: 20
  signal: 12

macd_16_24_6:
  fast: 16
  slow: 24
  signal: 6

macd_16_24_9:
  fast: 16
  slow: 24
  signal: 9

macd_16_24_12:
  fast: 16
  slow: 24
  signal: 12

macd_16_26_6:
  fast: 16
  slow: 26
  signal: 6

macd_16_26_9:
  fast: 16
  slow: 26
  signal: 9

macd_16_26_12:
  fast: 16
  slow: 26
  signal: 12

macd_16_28_6:
  fast: 16
  slow: 28
  signal: 6

macd_16_28_9:
  fast: 16
  slow: 28
  signal: 9

macd_16_28_12:
  fast: 16
  slow: 28
  signal: 12

macd_16_30_6:
  fast: 16
  slow: 30
  signal: 6

macd_16_30_9:
  fast: 16
  slow: 30
  signal: 9

macd_16_30_12:
  fast: 16
  slow: 30
  signal: 12
