
macd_8_20_6:
  fast: 8
  slow: 20
  signal: 6

macd_8_20_9:
  fast: 8
  slow: 20
  signal: 9

macd_8_20_12:
  fast: 8
  slow: 20
  signal: 12

macd_8_24_6:
  fast: 8
  slow: 24
  signal: 6

macd_8_24_9:
  fast: 8
  slow: 24
  signal: 9

macd_8_24_12:
  fast: 8
  slow: 24
  signal: 12

macd_8_26_6:
  fast: 8
  slow: 26
  signal: 6

macd_8_26_9:
  fast: 8
  slow: 26
  signal: 9

macd_8_26_12:
  fast: 8
  slow: 26
  signal: 12

macd_8_28_6:
  fast: 8
  slow: 28
  signal: 6

macd_8_28_9:
  fast: 8
  slow: 28
  signal: 9

macd_8_28_12:
  fast: 8
  slow: 28
  signal: 12

macd_8_30_6:
  fast: 8
  slow: 30
  signal: 6

macd_8_30_9:
  fast: 8
  slow: 30
  signal: 9

macd_8_30_12:
  fast: 8
  slow: 30
  signal: 12
