
stochrsi_7_7_2_2:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 2
  d_smooth: 2

stochrsi_7_7_2_3:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 2
  d_smooth: 3

stochrsi_7_7_2_4:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 2
  d_smooth: 4

stochrsi_7_7_3_2:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 3
  d_smooth: 2

stochrsi_7_7_3_3:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 3
  d_smooth: 3

stochrsi_7_7_3_4:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 3
  d_smooth: 4

stochrsi_7_7_4_2:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 4
  d_smooth: 2

stochrsi_7_7_4_3:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 4
  d_smooth: 3

stochrsi_7_7_4_4:
  rsi_period: 7
  stochrsi_period: 7
  k_smooth: 4
  d_smooth: 4
